language: python

python:
  - 3.6

sudo: required
dist: trusty
addons:
  postgresql: "9.6"

services:
  - postgresql

env:
  - DJANGO_SETTINGS_MODULE="decide.settings"

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "create user decide with password 'decide'" -U postgres
  - psql -c "create database decide owner decide" -U postgres

script:
  - python ./decide/manage.py makemigrations
  - python ./decide/manage.py migrate
  - git archive --format zip --output ./decide.zip master

before_deploy:
  - git config --local user.name davigldom
  - git config --local user.email davigldom@gmail.com
  - export GIT_TAG=1.0.20
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI build 20"
  - git push origin $GIT_TAG
  
deploy:
  provider: releases
  api_key: ed8a36f8d954a1da918fc2eb661fd5dbb56be9c8
  file: ./decide.zip
  skip_cleanup: true
  on:
    tags: true

notifications:
    email: false