language: python

python:
  - 3.6

sudo: required
dist: trusty
addons:
  postgresql: "9.6"

services:
  - postgresql

env:
  - DJANGO_SETTINGS_MODULE="decide.settings"

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "create user decide with password 'decide'" -U postgres
  - psql -c "create database decide owner decide" -U postgres

script:
  - python ./decide/manage.py makemigrations
  - python ./decide/manage.py migrate
  - git archive --format zip --output ./decide.zip master

before_deploy:
  - git config --local user.name davigldom
  - git config --local user.email davigldom@gmail.com
  # - export GIT_TAG=1.0.22
  - git tag 1.0.22
  # - git push https://github.com/decide-ganimedes-autenticacion/decide-ganimedes-autenticacion.git --tags
  
deploy:
  provider: releases
  api_key: 6d67901d88e77700db6bb8386c7729017d20cbd7
  file: ./decide.zip
  skip_cleanup: true
  on:
    tags: false

notifications:
    email: false