language: python 

python: 
- '3.6'
- '3.3'
- '2.7'
env: 
- DJANGO_VERSION=2.0 DB=postgres
- DJANGO_VERSION=1.10.8 DB=postgres
- DJANGO_VERSION=1.11.5 DB=postgres

sudo: required
dist: trusty
addons:
  postgresql: '9.6'
  
services:
- postgresql

global:
  - PGPORT=5432
  
before_install: 
- cd decide

install:
- pip install -q Django==$DJANGO_VERSION
- python setup.py -q install 
- pip install -r ../requirements.txt

before_script: 
- cp local_settings.example.py local_settings.py
- psql -c "create user decide with password 'decide'"
- psql -c "create database decide owner decide"

script:
- python3 ./decide/manage.py makemigrations
- python3 ./decide/manage.py migrate 
- python3 ./decide/manage.py test
- if [[ $TRAVIS_BRANCH == $RAMA_TRAVIS ]] && [[ $DEPLOY_TRAVIS == "1" ]]; then git archive --format zip --output ./$NOMBRE_ZIP.zip $RAMA_TRAVIS; echo "Zip generado correctamente."; fi

before_deploy:
- git config --local user.name $USER_TRAVIS
- git config --local user.email $EMAIL_TRAVIS
- git tag -a $GIT_TAG -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER"

deploy:
  provider: releases
  api-key:
    secure: $TOKEN_TRAVIS
  file: "./$NOMBRE_ZIP.zip"
  skip_cleanup: true
  on:
    branch: $RAMA_TRAVIS
    condition: $DEPLOY_TRAVIS = 1
tags: false

notifications:
  email:
    recipients:
      - did2505@gmail.com
      - davigldom@gmail.com
    on_success: always # default: change
    on_failure: always # default: always
    
branches:
  only:
  - master
  - desarrollo
